### ISSUE TITLE
Inconsistency with help behavior

### ISSUE THREAD

**Issue by robertp** [anchore/anchore-cli#128] opened 2020-10-01 16:39 UTC
Usage/help is only available for some commands or subcommands if there's a running Anchore Engine to talk to:

```
$ anchore-cli --u admin --p foobar analysis-archive -h
Usage: anchore-cli analysis-archive [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  images  Archive operations
  rules   Archive operations


$ anchore-cli --u admin --p foobar analysis-archive images -h
Error: could not access anchore service (user=admin url=http://localhost:8228/v1)
```

**Comment by nightfurys** [comment] 2021-07-08 21:44
@dspalmer99 the PR needs to be rebased. Can we get it reviewed and merged for next release?

**Comment by nightfurys** [comment] 2021-07-08 22:06
Closing this as a duplicate of #26

**Closed by nightfurys** 2021-07-08 22:06 UTC
Labels: bug, triaged
