### ISSUE TITLE
If image content output is piped or redirected, you get a unicode error

### ISSUE THREAD

**Issue by juledwar** [anchore/anchore-cli#27] opened 2019-02-26 22:11 UTC
Example:
```
anchore-cli image content bc5085cee55bbb6a7a99602e068955f1c76de8fcffe3482b39d1d8c8f48b18c3 files |tee foo
Error: 'ascii' codec can't encode character u'\xed' in position 393550: ordinal not in range(128)
```

```
$ anchore-cli --version
anchore-cli, version 0.2.4
```

**Comment by zhill** [comment] 2020-01-17 22:00
Is this still an issue? If so, can you provide an example of the output that when piped causes the error?

**Comment by juledwar** [comment] 2020-01-22 00:20
I can't reproduce this any more, however the exact image that caused the issue (from python:3-slim) doesn't seem to be around any more so it's hard to say whether it's fixed or newer images don't exhibit the problem.

**Comment by alfredodeza** [comment] 2020-01-29 21:47
I tried to reproduce this with Python 2.7, 3.5, 3.6, 3.7, and 3.8 without being able to trigger it.  I suspect that the handling of unicode in anchore-cli's internals changed for the better! 

Please feel free to re-open if you find this issue again. Closing for now as I can't reproduce

**Closed by alfredodeza** 2020-01-29 21:47 UTC
